import { Body, Controller, Get, Param, ParseIntPipe, Post, Query, UseGuards } from '@nestjs/common';
import { TransferStatus } from '@prisma/client';
import {
  ApiConflictResponse,
  ApiOkResponse,
  ApiOperation,
  ApiQuery,
  ApiSecurity,
  ApiTags,
  ApiUnauthorizedResponse,
  ApiUnprocessableEntityResponse,
} from '@nestjs/swagger';

import { ApiKeyGuard, GOV_API_KEY_SECURITY } from '../common/api-key.guard';
import { RejectTransferDto, SubmitTransferDto, TransferPreviewDto } from './dto/transfer.dto';
import {
  TransferApprovalResponseDto,
  TransferPreviewResult,
  TransferRequestDto,
} from './dto/transfer.response.dto';
import { TransfersService } from './transfers.service';

/**
 * TransfersController — base path /api/transfers.
 *
 * Every route here is officer-only (D47). D28 originally left preview and submit
 * open, on the reasoning that projecting a root involves no judgement — but that
 * assumed the two parties drove the transaction themselves. They do not: buyer
 * and seller meet at a government office and an officer operates the flow, so
 * the whole use case sits behind the API key.
 *
 * The guards stay per-method rather than on the class, because the OpenAPI
 * document has to keep saying which routes are gated and why — a class-level
 * decorator would flatten that back into an undifferentiated wall.
 *
 * This does NOT extend to /api/proof/* (D39), which stays open: the caller there
 * is an owner, a buyer or a bank, never an officer.
 */
@ApiTags('Transfers')
@Controller('transfers')
export class TransfersController {
  constructor(private readonly transfers: TransfersService) {}

  @Post('preview')
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({
    summary: 'Project the tree after a transfer (officer-only, read-only)',
    description:
      'D28 step 2. Computing the projected root reveals nothing and needs no judgement, so it ' +
      'stays automatic — but behind the API key (D47), because an officer runs the counter. Nothing is persisted and no root is published. The returned ' +
      'siblings/pathIndices are private inputs for transfer.circom — the old path comes from ' +
      'here rather than the receipt, because a receipt issued before someone else transferred ' +
      'carries a stale path.',
  })
  @ApiOkResponse({ type: TransferPreviewResult })
  preview(@Body() dto: TransferPreviewDto) {
    return this.transfers.preview(dto);
  }

  /** Queue a generated transfer proof for approval. */
  @Post()
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({
    summary: 'Submit a transfer proof for approval (officer-only)',
    description:
      'D28 step 3. The proof must be generated by both parties in one session; build it with ' +
      '`pnpm --filter blockchain run transfer:smoke <bundle-dir>` — it cannot be written by hand. ' +
      'Rejected here if the timestamp is stale (D26), the proof fails off-chain verification, ' +
      'or its oldMerkleRoot is no longer the current root.',
  })
  @ApiOkResponse({ type: TransferRequestDto })
  @ApiUnprocessableEntityResponse({
    description: 'Stale timestamp, invalid proof, or the root moved on',
  })
  @ApiConflictResponse({
    description:
      'A transfer for this property is already pending, or already approved and waiting to be ' +
      'published in a change set (D46)',
  })
  submit(@Body() dto: SubmitTransferDto) {
    return this.transfers.submit(dto);
  }

  @Get()
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({ summary: 'List transfer requests (officer)' })
  @ApiQuery({ name: 'status', required: false, enum: TransferStatus })
  @ApiOkResponse({ type: [TransferRequestDto] })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid x-gov-api-key header' })
  list(@Query('status') status?: TransferStatus) {
    return this.transfers.list(status);
  }

  /** The human decision: verify on-chain, then record the approval. */
  @Post(':id/approve')
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({
    summary: 'Approve a transfer (officer)',
    description:
      'D28 step 4 — the step that needs a person. A transfer proof shows someone holds the old ' +
      "owner's secret; it cannot show they ARE the old owner (ownerCommitment is pseudonymous, " +
      'D8). Verifies on chain, then moves the request from PENDING to APPROVED. Publishing the ' +
      'new root — and applying it to the registry — happens later, when a change set batches ' +
      'every approved transfer (and revocation) and an officer signs it (D46).',
  })
  @ApiOkResponse({ type: TransferApprovalResponseDto })
  @ApiUnprocessableEntityResponse({
    description:
      'Typed rejection from LandRegistryVerifier (D33): InvalidProof, RootMismatch (the registry ' +
      'moved on — the request is auto-rejected), or StaleTimestamp',
  })
  @ApiConflictResponse({ description: 'Request was already approved or rejected' })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid x-gov-api-key header' })
  approve(@Param('id', ParseIntPipe) id: number) {
    return this.transfers.approve(id);
  }

  @Post(':id/reject')
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({ summary: 'Reject a transfer request (officer)' })
  @ApiOkResponse({ type: TransferRequestDto })
  @ApiConflictResponse({ description: 'Request was already approved or rejected' })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid x-gov-api-key header' })
  reject(@Param('id', ParseIntPipe) id: number, @Body() dto: RejectTransferDto) {
    return this.transfers.reject(id, dto.reason);
  }
}
