/**
 * features/government/wallet/registry.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * Everything the portal needs to talk to RootRegistry that is not a React hook:
 * the ABI, the decimal ⇄ bytes32 root codec, which function a draft publishes
 * with, and what a wallet failure means.
 *
 * ABI source (D54). The runtime ABI is the compiler's own output
 * (`blockchain/artifacts/.../RootRegistry.json`, regenerated by
 * `pnpm run compile`) and its TYPE is typechain's `as const` ABI through a
 * type-only import — so wagmi calls are fully typed, nothing is hand-written,
 * and ethers (which the typechain factory classes extend) never enters the
 * bundle. The address is not here at all: it comes from GET /government/status.
 */

import type { RootRegistry__factory } from '@land-registry/blockchain/typechain-types';
import rootRegistryArtifact from '@land-registry/blockchain/artifacts/contracts/RootRegistry.sol/RootRegistry.json';
import { type Hex, hexToBigInt, toHex } from 'viem';

import type { OpenDraft } from '../api/types';

export const rootRegistryAbi = rootRegistryArtifact.abi as unknown as typeof RootRegistry__factory.abi;

/** A Merkle root as the API speaks it (decimal) → the bytes32 the contract stores. */
export function rootToBytes32(root: string): Hex {
  return toHex(BigInt(root), { size: 32 });
}

/** The contract's bytes32 root → the decimal string the API and drafts use. */
export function bytes32ToDecimal(root: Hex): string {
  return hexToBigInt(root).toString();
}

export type PublishCall =
  | { functionName: 'publishRoot'; args: readonly [Hex] }
  | {
      functionName: 'publishRootWithRevocations';
      args: readonly [Hex, readonly bigint[], readonly number[], readonly Hex[]];
    };

/**
 * The transaction a draft is published with — same rule as transferSmoke.ts:
 * an issuance round is always `publishRoot`; a change set uses
 * `publishRootWithRevocations` only when it revokes something, since that is
 * the function that also writes the public `revocations` mapping (D45).
 *
 * Signing `publishRoot` for a round that has revocations would still let
 * confirm() succeed (the root matches) while leaving the on-chain audit trail
 * empty — which is why this choice is made here, once, and not per screen.
 */
export function publishCallFor(draft: OpenDraft): PublishCall {
  const newRoot = rootToBytes32(draft.newRoot);
  if (draft.kind === 'changeset' && draft.revocationIds.length > 0) {
    const { propertyIds, reasonCodes, detailHashes } = draft.revocationCalldata;
    return {
      functionName: 'publishRootWithRevocations',
      args: [newRoot, propertyIds.map((id) => BigInt(id)), reasonCodes, detailHashes],
    };
  }
  return { functionName: 'publishRoot', args: [newRoot] };
}

export type WalletErrorCode =
  | 'rejected'
  | 'duplicate-root'
  | 'no-role'
  | 'already-revoked'
  | 'invalid-revocation'
  | 'unknown';

const REVERT_CODES: Record<string, WalletErrorCode> = {
  DuplicateRoot: 'duplicate-root',
  AccessControlUnauthorizedAccount: 'no-role',
  AlreadyRevoked: 'already-revoked',
  InvalidReasonCode: 'invalid-revocation',
  RevocationArrayLengthMismatch: 'invalid-revocation',
};

/**
 * What a failed wallet call means, for the screen to explain. Walks the
 * `cause` chain the way viem's BaseError.walk() does, looking for a cancelled
 * signature (EIP-1193 code 4001) or a decoded RootRegistry custom error.
 */
export function walletErrorCode(error: unknown): WalletErrorCode {
  for (let node = error as Record<string, unknown> | undefined, depth = 0; node && depth < 10; depth++) {
    if (node.name === 'UserRejectedRequestError' || node.code === 4001) return 'rejected';
    const data = node.data as { errorName?: unknown } | undefined;
    const errorName = typeof data?.errorName === 'string' ? data.errorName : undefined;
    if (errorName) return REVERT_CODES[errorName] ?? 'unknown';
    node = node.cause as Record<string, unknown> | undefined;
  }
  return 'unknown';
}
