/**
 * lib/contracts.ts - the two contract ABIs and the root codec, for both portals.
 *
 * ABI SOURCE (D54, promoted to shared code by D66). The runtime ABI is the
 * compiler's own output (`blockchain/artifacts/.../<C>.json`, regenerated by
 * `pnpm run compile`) and its TYPE is typechain's `as const` ABI through a
 * type-only import. So calls are fully typed, nothing is hand-written, and
 * ethers — which the typechain factory classes extend — never enters the
 * bundle. Addresses are NOT here: the government portal reads them from
 * `GET /api/government/status`, the resident portal from
 * `GET /api/public/config` (D58).
 *
 * Taking the ABI from the artifact rather than a hand-written fragment is also
 * what makes the verifier's custom errors decodable: viem can only name
 * `InvalidProof` / `RootMismatch` / `StaleTimestamp` in a reverted `eth_call`
 * if the ABI carries their `error` entries, and the compiler's does.
 *
 * ⚠️ `pnpm run compile` is a precondition for `dev` and `build` — the artifacts
 *    are gitignored.
 */

import type {
  LandRegistryVerifier__factory,
  RootRegistry__factory,
} from '@land-registry/blockchain/typechain-types';
import landRegistryVerifierArtifact from '@land-registry/blockchain/artifacts/contracts/LandRegistryVerifier.sol/LandRegistryVerifier.json';
import rootRegistryArtifact from '@land-registry/blockchain/artifacts/contracts/RootRegistry.sol/RootRegistry.json';
import { type Hex, hexToBigInt, toHex } from 'viem';

export const rootRegistryAbi = rootRegistryArtifact.abi as unknown as typeof RootRegistry__factory.abi;

export const landRegistryVerifierAbi =
  landRegistryVerifierArtifact.abi as unknown as typeof LandRegistryVerifier__factory.abi;

/** A Merkle root as the API speaks it (decimal) → the bytes32 the contract stores. */
export function rootToBytes32(root: string): Hex {
  return toHex(BigInt(root), { size: 32 });
}

/** The contract's bytes32 root → the decimal string the API and drafts use. */
export function bytes32ToDecimal(root: Hex): string {
  return hexToBigInt(root).toString();
}
