import { Body, Controller, Get, Param, ParseIntPipe, Post, Query, UseGuards } from '@nestjs/common';
import { TransferStatus } from '@prisma/client';
import {
  ApiConflictResponse,
  ApiOkResponse,
  ApiOperation,
  ApiQuery,
  ApiSecurity,
  ApiTags,
  ApiUnauthorizedResponse,
  ApiUnprocessableEntityResponse,
} from '@nestjs/swagger';

import { ApiKeyGuard } from './api-key.guard';
import {
  RejectTransferDto,
  SubmitTransferDto,
  TransferPreviewDto,
  TransferPreviewResult,
} from './dto/transfer.dto';
import { TransferApprovalResponseDto, TransferRequestDto } from './dto/transfer.response.dto';
import { TransfersService } from './transfers.service';
import { GOV_API_KEY_SECURITY } from '../swagger';

/**
 * TransfersController — base path /api/transfers.
 *
 * The guard boundary IS the design (D28): preview and submit are open because
 * they involve no judgement and change nothing, while listing and deciding
 * belong to an officer at the authority.
 */
@ApiTags('Transfers')
@Controller('transfers')
export class TransfersController {
  constructor(private readonly transfers: TransfersService) {}

  @Post('preview')
  @ApiOperation({
    summary: 'Project the tree after a transfer (public, read-only)',
    description:
      'D28 step 2. Computing the projected root reveals nothing and needs no judgement, so this ' +
      'is open and automatic. Nothing is persisted and no root is published. The returned ' +
      'siblings/pathIndices are private inputs for transfer.circom — the old path comes from ' +
      'here rather than the receipt, because a receipt issued before someone else transferred ' +
      'carries a stale path.',
  })
  @ApiOkResponse({ type: TransferPreviewResult })
  preview(@Body() dto: TransferPreviewDto) {
    return this.transfers.preview(dto);
  }

  /** Queue a generated transfer proof for approval. */
  @Post()
  @ApiOperation({
    summary: 'Submit a transfer proof for approval (public)',
    description:
      'D28 step 3. The proof must be generated by both parties in one session; build it with ' +
      '`pnpm --filter blockchain run transfer:smoke <bundle-dir>` — it cannot be written by hand. ' +
      'Rejected here if the timestamp is stale (D26), the proof fails off-chain verification, ' +
      'or its oldMerkleRoot is no longer the current root.',
  })
  @ApiOkResponse({ type: TransferRequestDto })
  @ApiUnprocessableEntityResponse({
    description: 'Stale timestamp, invalid proof, or the root moved on',
  })
  @ApiConflictResponse({ description: 'A transfer for this property is already pending' })
  submit(@Body() dto: SubmitTransferDto) {
    return this.transfers.submit(dto);
  }

  @Get()
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({ summary: 'List transfer requests (officer)' })
  @ApiQuery({ name: 'status', required: false, enum: TransferStatus })
  @ApiOkResponse({ type: [TransferRequestDto] })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid x-gov-api-key header' })
  list(@Query('status') status?: TransferStatus) {
    return this.transfers.list(status);
  }

  /** The human decision: verify on-chain, then publish the new root. */
  @Post(':id/approve')
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({
    summary: 'Approve a transfer and publish the new root (officer)',
    description:
      'D28 step 4 — the step that needs a person. A transfer proof shows someone holds the old ' +
      "owner's secret; it cannot show they ARE the old owner (ownerCommitment is pseudonymous, " +
      'D8). Verifies on chain, re-derives the projected root from current state, publishes, then ' +
      'updates the database. Afterwards the proof is spent: its oldMerkleRoot is no longer latest.',
  })
  @ApiOkResponse({ type: TransferApprovalResponseDto })
  @ApiUnprocessableEntityResponse({
    description:
      'Typed rejection from LandRegistryVerifier (D33): InvalidProof, RootMismatch (the registry ' +
      'moved on — the request is auto-rejected), or StaleTimestamp',
  })
  @ApiConflictResponse({ description: 'Request was already approved or rejected' })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid x-gov-api-key header' })
  approve(@Param('id', ParseIntPipe) id: number) {
    return this.transfers.approve(id);
  }

  @Post(':id/reject')
  @UseGuards(ApiKeyGuard)
  @ApiSecurity(GOV_API_KEY_SECURITY)
  @ApiOperation({ summary: 'Reject a transfer request (officer)' })
  @ApiOkResponse({ type: TransferRequestDto })
  @ApiConflictResponse({ description: 'Request was already approved or rejected' })
  @ApiUnauthorizedResponse({ description: 'Missing or invalid x-gov-api-key header' })
  reject(@Param('id', ParseIntPipe) id: number, @Body() dto: RejectTransferDto) {
    return this.transfers.reject(id, dto.reason);
  }
}
